questions = [
    ["What does AI stand for?", "Artificial Intelligence", "Automatic Internet", "Advanced Interface", "Artificial Internet", 1],
    ["Which programming language is most commonly used for Machine Learning?", "Python", "Java", "C", "PHP", 1],
    ["Which library is mainly used for Machine Learning in Python?", "Scikit-learn", "NumPy", "Flask", "Tkinter", 1],
    ["Which library is mainly used for Deep Learning?", "TensorFlow", "BeautifulSoup", "OpenCV", "Pandas", 1],
    ["Machine Learning is a subset of?", "Artificial Intelligence", "Data Mining", "Networking", "Cyber Security", 1],
    ["Which type of learning uses labeled data?", "Supervised Learning", "Unsupervised Learning", "Reinforcement Learning", "Transfer Learning", 1],
    ["Which learning algorithm works with unlabeled data?", "Unsupervised Learning", "Supervised Learning", "Deep Learning", "Regression", 1],
    ["Which algorithm is used for classification?", "Decision Tree", "Linear Regression", "K-Means", "Apriori", 1],
    ["Which algorithm is commonly used for clustering?", "K-Means", "Random Forest", "Logistic Regression", "Naive Bayes", 1],
    ["Which algorithm predicts continuous values?", "Linear Regression", "KNN", "Decision Tree", "K-Means", 1],
    ["CNN stands for?", "Convolutional Neural Network", "Computer Neural Network", "Central Neural Network", "Connected Neural Network", 1],
    ["RNN stands for?", "Recurrent Neural Network", "Random Neural Network", "Recursive Network Node", "Reinforced Neural Network", 1],
    ["Which activation function outputs values between 0 and 1?", "Sigmoid", "ReLU", "Tanh", "Softmax", 1],
    ["Which activation function is most commonly used in hidden layers?", "ReLU", "Sigmoid", "Linear", "Softmax", 1],
    ["Which neural network is commonly used for image recognition?", "CNN", "RNN", "Naive Bayes", "KNN", 1],
    ["Which neural network is best suited for sequence data?", "RNN", "CNN", "Linear Regression", "Decision Tree", 1],
    ["What does NLP stand for?", "Natural Language Processing", "Natural Learning Process", "Network Language Processing", "Neural Learning Program", 1],
    ["Which AI field deals with understanding human language?", "Natural Language Processing", "Computer Vision", "Robotics", "Expert Systems", 1],
    ["Which AI field deals with image analysis?", "Computer Vision", "Speech Recognition", "Data Mining", "Natural Language Processing", 1],
    ["Which metric is commonly used to evaluate classification models?", "Accuracy", "RMSE", "MAE", "MSE", 1],
    ["Which metric is commonly used for regression problems?", "Mean Squared Error", "Precision", "Recall", "F1 Score", 1],
    ["Which dataset is used to evaluate a trained model?", "Test Set", "Training Set", "Feature Set", "Label Set", 1],
    ["Which dataset is used to train a machine learning model?", "Training Set", "Validation Set", "Test Set", "Prediction Set", 1],
    ["What is overfitting?", "Model memorizes training data", "Model is too simple", "Model has fewer features", "Model ignores data", 1],
    ["Which technique helps reduce overfitting?", "Regularization", "Duplication", "Normalization Only", "Sorting", 1],
    ["Which algorithm is an ensemble learning method?", "Random Forest", "K-Means", "Linear Regression", "KNN", 1],
    ["What does GPU stand for?", "Graphics Processing Unit", "General Processing Unit", "Global Processor Unit", "Graph Programming Unit", 1],
    ["Which company developed TensorFlow?", "Google", "Microsoft", "IBM", "Amazon", 1],
    ["Which company developed PyTorch?", "Meta", "Google", "Apple", "Intel", 1],
    ["Which AI model powers ChatGPT?", "GPT", "BERT", "AlexNet", "VGG", 1],
    ["What does KNN stand for?", "K-Nearest Neighbors", "Knowledge Neural Network", "Kernel Neural Network", "Key Node Network", 1],
    ["Which algorithm is commonly used for spam email detection?", "Naive Bayes", "K-Means", "Linear Regression", "Apriori", 1],
    ["Which algorithm is used for dimensionality reduction?", "PCA", "KNN", "Decision Tree", "Random Forest", 1],
    ["What does PCA stand for?", "Principal Component Analysis", "Primary Component Algorithm", "Parallel Component Analysis", "Principal Clustering Algorithm", 1],
    ["Which algorithm is widely used for recommendation systems?", "Collaborative Filtering", "K-Means", "Decision Tree", "Linear Regression", 1],
    ["Which optimizer is most commonly used in deep learning?", "Adam", "Gradient Boosting", "KNN", "Apriori", 1],
    ["What does ReLU stand for?", "Rectified Linear Unit", "Reduced Linear Unit", "Recursive Learning Unit", "Random Linear Unit", 1],
    ["Which activation function can output negative values?", "Tanh", "Sigmoid", "ReLU", "Softmax", 1],
    ["Which layer is the first layer in a neural network?", "Input Layer", "Hidden Layer", "Output Layer", "Activation Layer", 1],
    ["Which layer produces the final prediction?", "Output Layer", "Input Layer", "Hidden Layer", "Pooling Layer", 1],
    ["What is the purpose of a loss function?", "Measure prediction error", "Store training data", "Normalize features", "Split dataset", 1],
    ["Which loss function is commonly used for classification?", "Cross-Entropy Loss", "Mean Squared Error", "MAE", "Huber Loss", 1],
    ["Which loss function is commonly used for regression?", "Mean Squared Error", "Cross-Entropy Loss", "Binary Loss", "Softmax Loss", 1],
    ["Which technique randomly drops neurons during training?", "Dropout", "Batch Normalization", "Pooling", "Gradient Descent", 1],
    ["Which optimization algorithm updates weights using gradients?", "Gradient Descent", "K-Means", "PCA", "Decision Tree", 1],
    ["Which algorithm is used for object detection?", "YOLO", "KNN", "Naive Bayes", "Apriori", 1],
    ["YOLO stands for?", "You Only Look Once", "Your Object Learning Output", "Yield Object Localization", "Young Object Learning", 1],
    ["Which model is famous for image classification?", "ResNet", "Word2Vec", "LSTM", "BERT", 1],
    ["Which neural network is designed for long-term sequence learning?", "LSTM", "CNN", "MLP", "KNN", 1],
    ["LSTM stands for?", "Long Short-Term Memory", "Long Sequential Training Model", "Linear State Transition Model", "Learning Sequence Transfer Method", 1],
    ["Which AI technique is used for playing games like Chess and Go?", "Reinforcement Learning", "Supervised Learning", "Unsupervised Learning", "Regression", 1],
    ["Which term refers to the input variables of a dataset?", "Features", "Labels", "Targets", "Classes", 1],
    ["Which term refers to the expected output in supervised learning?", "Label", "Feature", "Cluster", "Attribute", 1],
    ["Which Python library is mainly used for data manipulation?", "Pandas", "TensorFlow", "Flask", "OpenCV", 1],
    ["Which Python library is mainly used for numerical computations?", "NumPy", "Tkinter", "Flask", "BeautifulSoup", 1],
    ["Which Python library is commonly used for data visualization?", "Matplotlib", "TensorFlow", "Scikit-learn", "OpenCV", 1],
    ["Which library provides high-level statistical visualizations?", "Seaborn", "Flask", "NumPy", "Tkinter", 1],
    ["Which AI branch focuses on enabling machines to understand speech?", "Speech Recognition", "Computer Vision", "Robotics", "Expert Systems", 1],
    ["Which technique scales feature values to a common range?", "Normalization", "Clustering", "Bagging", "Boosting", 1],
    ["Which technique combines multiple weak learners into a strong learner?", "Boosting", "Normalization", "Dropout", "Pooling", 1]
]



LEVELS = [
    "100",
    "200",
    "500",
    "1,000",
    "2,000",
    "5,000",
    "10,000",
    "20,000",
    "40,000",
    "1 Lakh",
    "2.5 Lakh",
    "5 Lakh",
    "10 Lakh",
    "25 Lakh",
    "50 Lakh",
    "1 Crore"
]

